import os
import sys
import time

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm
    from rich.table import Table
    from rich import print as rprint
except ImportError:
    print("Missing requirements. Installing automatically...")
    os.system(f"{sys.executable} -m pip install rich>=13.0")
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm
    from rich.table import Table

console = Console()

def clear_screen():
    os.system("cls" if os.name == "nt" else "clear")

def detect_imap_host(email: str) -> str:
    domain = email.split("@")[-1].lower() if "@" in email else ""
    if domain in ["gmail.com", "googlemail.com"]:
        return "imap.gmail.com"
    elif domain in ["outlook.com", "hotmail.com", "live.com"]:
        return "outlook.office365.com"
    elif domain in ["yahoo.com", "ymail.com", "rocketmail.com"]:
        return "imap.mail.yahoo.com"
    elif domain in ["icloud.com", "me.com", "mac.com"]:
        return "imap.mail.me.com"
    return ""

def provider_help(host: str):
    if "gmail.com" in host:
        return "Go to your Google Account -> Security -> 2-Step Verification -> App Passwords."
    elif "outlook" in host:
        return "Go to Microsoft Account -> Security -> Advanced Security Options -> App Passwords."
    elif "yahoo" in host:
        return "Go to Yahoo Account Security -> Generate app password."
    elif "me.com" in host:
        return "Go to Apple ID -> Sign-In and Security -> App-Specific Passwords."
    return "Search your email provider's help docs for 'IMAP App Password'."

def setup_wizard():
    clear_screen()
    console.print(Panel.fit("[bold cyan]🛡️  DomainShield - Easy Setup Wizard[/bold cyan]", border_style="cyan"))
    console.print("\nLet's get your personal email connected. It takes just a minute!\n")

    # 1. Email Address
    email = Prompt.ask("[bold yellow]1. What is your email address?[/]")
    
    # Auto-detect host
    host = detect_imap_host(email)
    if host:
        console.print(f"[green]✓ Detected provider:[/] {host}")
    else:
        host = Prompt.ask("[bold yellow]What is your IMAP server address? (e.g. imap.mail.com)[/]")

    # 2. App Password
    console.print("\n[bold yellow]2. App Password Required[/]")
    console.print(f"[dim]{provider_help(host)}[/]")
    console.print("This is a special 16-character password just for this app to scan your inbox.")
    password = Prompt.ask("[bold yellow]Paste your App Password[/]", password=True)

    # 3. Whitelist
    console.print("\n[bold yellow]3. Trusted Domains[/]")
    console.print("We will block ALL emails unless they come from these trusted domains.")
    console.print("[dim]Example: netflix.com, chase.com, amazon.com, yourboss.com[/]")
    whitelist_raw = Prompt.ask("[bold yellow]Enter domains you trust (comma separated)[/]")
    
    whitelist = [d.strip() for d in whitelist_raw.split(",") if d.strip()]
    if not whitelist:
        whitelist = ["gmail.com", "yahoo.com"]  # fallback just so it doesn't crash
        
    # Write to env file
    env_content = f"""# Auto-generated by Easy Start
WHITELIST_DOMAINS={",".join(whitelist)}
STRICT_MODE=false
ALERT_THRESHOLD=all
IMAP_HOST={host}
IMAP_PORT=993
IMAP_USER={email}
IMAP_PASSWORD={password}
IMAP_FOLDER=INBOX
MAX_EMAILS=20
"""
    os.makedirs("config", exist_ok=True)
    with open("config/config.env", "w", encoding="utf-8") as f:
        f.write(env_content)
        
    try:
        import run
        run._dump_ui_config(run._load_env())
    except ImportError:
        pass
        
    console.print("\n[bold green]✓ Setup Complete! Saved to config/config.env[/bold green]")
    time.sleep(2)

def run_agent():
    import run  # Imports the run.py script logic
    from domain_shield_agent import DomainShieldAgent, AgentContext
    
    # Load env variables (run.py has a _load_env helper)
    env = run._load_env()
    
    context_inputs = {
        "source": "imap",
        "raw_eml": "",
        "eml_path": "",
        "whitelist_domains": env["whitelist_domains"],
        "strict_mode": env["strict_mode"],
        "alert_threshold": env["alert_threshold"],
        "webhook_url": env["webhook_url"],
        "webhook_format": env["webhook_format"],
        "imap_host": env["imap_host"],
        "imap_port": env["imap_port"],
        "imap_user": env["imap_user"],
        "imap_password": env["imap_password"],
        "imap_folder": env["imap_folder"],
        "max_emails": env["max_emails"],
    }
    
    agent = DomainShieldAgent()
    ctx = AgentContext(inputs=context_inputs)
    
    with console.status("[bold cyan]Scanning your inbox...[/bold cyan]", spinner="dots"):
        result = agent.execute(ctx)
        
    return result

def show_results(result):
    clear_screen()
    data = result.get("data", result)
    
    if result.get("status") == "error":
        console.print(Panel.fit(f"[bold red]Error during scan:[/bold red]\n{result.get('message')}", border_style="red"))
        return

    processed = data.get("processed_count", 0)
    
    console.print(Panel.fit(
        f"[bold white]Scan Complete![/]\n"
        f"Processed [cyan]{processed}[/] recent emails.\n"
        f"Safe: [green]{data.get('safe_count', 0)}[/] | "
        f"Suspicious: [red]{data.get('suspicious_count', 0)}[/]", 
        border_style="green" if data.get('suspicious_count', 0) == 0 else "red"
    ))

    if processed == 0:
        console.print("\n* Your INBOX has no unread/recent emails, or we couldn't connect.")
        return

    # Print a summary table
    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Result", style="dim", width=12)
    table.add_column("Sender", justify="left")
    table.add_column("Subject", justify="left", max_width=40)
    
    # To show the actual emails, we normally pull from the audit log or agent result
    # We can fetch flags from the summary if the agent returns it, but the agent 
    # only returns the alerts right now. We'll show the alerts.
    alerts = data.get("alerts", [])
    
    if not alerts:
        console.print("\n[bold green]✓ All recent emails were sent from your trusted domains. No phishing detected![/]")
    else:
        console.print("\n[bold red]⚠️ Suspicious Emails Found:[/bold red]")
        for alert in alerts:
            table.add_row(
                f"[red]{alert.get('risk_level')}[/red]", 
                alert.get("from_raw", "").split("<")[0].strip(),
                alert.get("subject", "")
            )
            table.add_row("", f"[dim italic]{alert.get('reasons', [''])[0]}[/]", "")
            table.add_row("", "", "") # spacer
            
        console.print(table)
        
def main():
    while True:
        clear_screen()
        console.print(Panel.fit(
            "[bold cyan]🛡️  DomainShield Personal[/bold cyan]\n"
            "[dim]The easiest way to block phishing emails.[/dim]",
            border_style="cyan"
        ))
        
        has_config = os.path.exists("config/config.env")
        
        if not has_config:
            console.print("\n[bold yellow]No configuration found. Let's set it up![/]")
            Prompt.ask("\nPress [bold green]Enter[/] to begin setup", default="")
            setup_wizard()
            continue
            
        console.print("\n[1] [bold green]Scan Inbox Now[/]")
        console.print("[2] [bold yellow]Re-configure Settings[/]")
        console.print("[3] [bold cyan]View Dashboard in Browser[/]")
        console.print("[4] [bold magenta]Manage Whitelist[/]")
        console.print("[5] [dim]Exit[/]")
        
        choice = Prompt.ask("\nWhat would you like to do?", choices=["1", "2", "3", "4", "5"], default="1")
        
        if choice == "1":
            res = run_agent()
            show_results(res)
            Prompt.ask("\nPress [bold]Enter[/] to return to menu", default="")
            
        elif choice == "2":
            setup_wizard()
            
        elif choice == "3":
            console.print("\n[bold cyan]Starting DomainShield Interactive Dashboard...[/]")
            console.print("[dim]The dashboard will open in your browser.[/dim]")
            console.print("[dim]Press Ctrl+C when you want to stop the dashboard and return here.[/dim]")
            time.sleep(1)
            try:
                os.system(f"{sys.executable} ui_server.py")
            except KeyboardInterrupt:
                pass
            console.print("\n[green]Dashboard stopped.[/green]")
            time.sleep(1)
            
        elif choice == "4":
            clear_screen()
            console.print(Panel.fit("[bold magenta]Manage Whitelist[/]"))
            env_file = "config/config.env"
            with open(env_file, "r") as f:
                lines = f.readlines()
            
            w_line_idx = -1
            current_domains = []
            for i, line in enumerate(lines):
                if line.startswith("WHITELIST_DOMAINS="):
                    w_line_idx = i
                    val = line.strip().split("=", 1)[1]
                    current_domains = [d for d in val.split(",") if d.strip()]
                    break
                    
            console.print(f"Current Trusted Domains: [bold green]{', '.join(current_domains)}[/]\n")
            new_domains_input = Prompt.ask("Enter domain(s) to ADD or REMOVE (comma separated, or press Enter to cancel)")
            if new_domains_input.strip():
                new_domains = [d.strip().lower() for d in new_domains_input.split(",") if d.strip()]
                added = []
                removed = []
                for domain in new_domains:
                    if domain not in current_domains:
                        current_domains.append(domain)
                        added.append(domain)
                    else:
                        current_domains.remove(domain)
                        removed.append(domain)
                        
                if added:
                    console.print(f"\n[bold green]✓ ADDED: {', '.join(added)}[/]")
                if removed:
                    console.print(f"\n[bold yellow]🚫 REMOVED: {', '.join(removed)}[/]")
                    
                lines[w_line_idx] = f"WHITELIST_DOMAINS={','.join(current_domains)}\n"
                with open(env_file, "w") as f:
                    f.writelines(lines)
                   
                # Dump UI config
                try:
                    import run
                    run._dump_ui_config(run._load_env())
                except ImportError:
                    pass
            time.sleep(2)
            
        elif choice == "5":
            console.print("\n[bold green]Stay safe![/]\n")
            break

if __name__ == "__main__":
    main()
