"""
ZAK scaffold templates used by `zak init`.

These are the template strings for YAML + Python agent class boilerplate per domain.
"""

from __future__ import annotations

from typing import NamedTuple


class DomainTemplate(NamedTuple):
    yaml_template: str
    python_template: str
    default_tools: list[str]
    default_allowed_actions: list[str]
    default_denied_actions: list[str]


DOMAIN_TEMPLATES: dict[str, DomainTemplate] = {
    "risk_quant": DomainTemplate(
        yaml_template="""\
agent:
  id: {agent_id}
  name: "{agent_name}"
  domain: risk_quant
  version: "1.0.0"

intent:
  goal: "Compute and update risk scores for critical assets"
  success_criteria:
    - "All assets have updated risk scores in the SIF graph"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.75

capabilities:
  tools:
    - read_asset
    - list_assets
    - list_vulnerabilities
    - compute_risk
    - write_risk_node
  data_access:
    - asset_inventory
    - vulnerability_scanner

boundaries:
  risk_budget: medium
  allowed_actions:
    - agent_execute
    - read_asset
    - list_assets
    - compute_risk
    - write_risk_node
  denied_actions:
    - delete_asset
    - delete_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
    - require_confidence_threshold
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
""",
        python_template="""\
\"\"\"
{agent_name} — ZAK Risk Quantification Agent.

Auto-generated by `zak init`. Implement execute() to define your agent's logic.
Register with: @register_agent(domain="risk_quant")
\"\"\"

from __future__ import annotations

from zak.core.runtime.agent import AgentContext, AgentResult, BaseAgent
from zak.core.runtime.registry import register_agent
from zak.core.tools.substrate import ToolExecutor
import zak.core.tools.builtins as tools  # noqa: F401


@register_agent(
    domain="risk_quant",
    description="{agent_name}",
    version="1.0.0",
)
class {class_name}(BaseAgent):
    \"\"\"
    {agent_name}

    Uses the ZAK risk propagation engine to compute and write risk scores.
    \"\"\"

    def execute(self, context: AgentContext) -> AgentResult:
        # 1. Load assets
        assets = ToolExecutor.call(tools.list_assets, context=context)

        results = []
        for asset in assets:
            # 2. Compute risk
            risk = ToolExecutor.call(
                tools.compute_risk,
                context=context,
                criticality=asset.get("criticality", "medium"),
                exposure=asset.get("exposure_level", "internal"),
            )
            results.append({{
                "asset_id": asset["node_id"],
                **risk,
            }})

        return AgentResult.ok(context, output={{"results": results}})
""",
        default_tools=["read_asset", "list_assets", "list_vulnerabilities", "compute_risk", "write_risk_node"],
        default_allowed_actions=["read_asset", "list_assets", "compute_risk", "write_risk_node"],
        default_denied_actions=["delete_asset"],
    ),
    "appsec": DomainTemplate(
        yaml_template="""\
agent:
  id: {agent_id}
  name: "{agent_name}"
  domain: appsec
  version: "1.0.0"

intent:
  goal: "Scan code and dependencies for security vulnerabilities"
  success_criteria:
    - "All critical/high findings identified and written to SIF"
  priority: high

reasoning:
  mode: rule_based
  autonomy_level: bounded
  confidence_threshold: 0.80

capabilities:
  tools:
    - sast_scan
    - dependency_scan
    - write_vulnerability_node
  data_access:
    - source_code
    - dependency_manifest

boundaries:
  risk_budget: low
  allowed_actions:
    - sast_scan
    - dependency_scan
    - write_vulnerability_node
  denied_actions:
    - modify_source_code
    - delete_dependency
  environment_scope:
    - staging
    - dev

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
""",
        python_template="""\
\"\"\"
{agent_name} — ZAK AppSec Agent.

Auto-generated by `zak init`. Implement execute() to define your agent's logic.
\"\"\"

from __future__ import annotations

from zak.core.runtime.agent import AgentContext, AgentResult, BaseAgent
from zak.core.runtime.registry import register_agent


@register_agent(
    domain="appsec",
    description="{agent_name}",
    version="1.0.0",
)
class {class_name}(BaseAgent):
    \"\"\"
    {agent_name}

    Performs SAST/DAST scanning and writes findings as VulnerabilityNodes to the SIF graph.
    \"\"\"

    def execute(self, context: AgentContext) -> AgentResult:
        findings: list[dict] = []

        # TODO: implement your SAST/DAST/dependency scanning logic here
        # Use ToolExecutor.call(tools.write_vulnerability_node, ...) to persist findings

        return AgentResult.ok(context, output={{"findings_count": len(findings), "findings": findings}})
""",
        default_tools=["sast_scan", "dependency_scan", "write_vulnerability_node"],
        default_allowed_actions=["sast_scan", "dependency_scan", "write_vulnerability_node"],
        default_denied_actions=["modify_source_code"],
    ),
    "vuln_triage": DomainTemplate(
        yaml_template="""\\
agent:
  id: {{agent_id}}
  name: "{{agent_name}}"
  domain: vuln_triage
  version: "1.0.0"

intent:
  goal: "Prioritize vulnerabilities based on risk"
  success_criteria:
    - "Vulnerabilities ranked by priority score"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.85

capabilities:
  tools:
    - list_vulnerabilities
    - read_asset
    - compute_priority
  data_access:
    - vulnerability_scanner
    - asset_inventory

boundaries:
  risk_budget: low
  allowed_actions:
    - list_vulnerabilities
    - read_asset
    - compute_priority
  denied_actions:
    - patch_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
  sandbox_profile: standard
  audit_level: standard
""",
        python_template="""\\
\"\"\"
{{agent_name}} — ZAK Vulnerability Triage Agent.
\"\"\"

from __future__ import annotations

from zak.core.runtime.agent import AgentContext, AgentResult, BaseAgent
from zak.core.runtime.registry import register_agent

@register_agent(
    domain="vuln_triage",
    description="{{agent_name}}",
    version="1.0.0",
)
class {{class_name}}(BaseAgent):
    def execute(self, context: AgentContext) -> AgentResult:
        # Implement vulnerability triage logic
        return AgentResult.ok(context, output={{"triaged_count": 0, "results": []}})
""",
        default_tools=["list_vulnerabilities", "read_asset", "compute_priority"],
        default_allowed_actions=["list_vulnerabilities", "read_asset", "compute_priority"],
        default_denied_actions=["patch_vulnerability"],
    ),
}
