/**
 * ZAK scaffold templates used by `zak init`.
 *
 * Contains domain-specific YAML + TypeScript agent class boilerplate
 * for each supported open-source security domain.
 *
 * TypeScript equivalent of zak/cli/templates.py.
 */

// ---------------------------------------------------------------------------
// DomainTemplate
// ---------------------------------------------------------------------------

export interface DomainTemplate {
  /** Security domain identifier. */
  domain: string;
  /** US-ADSL YAML template with {agentId}, {agentName} placeholders. */
  yamlTemplate: string;
  /** TypeScript agent class template with {agentId}, {agentName}, {className} placeholders. */
  tsTemplate: string;
}

// ---------------------------------------------------------------------------
// OSS Domains
// ---------------------------------------------------------------------------

/** The five open-source security domains available in the OSS edition. */
export const OSS_DOMAINS = [
  "generic",
  "risk_quant",
  "vuln_triage",
  "appsec",
  "compliance",
] as const;

export type OssDomain = (typeof OSS_DOMAINS)[number];

// ---------------------------------------------------------------------------
// Domain Templates
// ---------------------------------------------------------------------------

export const DOMAIN_TEMPLATES: Record<string, DomainTemplate> = {
  // -------------------------------------------------------------------------
  // Generic — a minimal starting point for any security domain
  // -------------------------------------------------------------------------
  generic: {
    domain: "generic",
    yamlTemplate: `\
agent:
  id: {agentId}
  name: "{agentName}"
  domain: appsec
  version: "1.0.0"

intent:
  goal: "Perform a general-purpose security analysis"
  success_criteria:
    - "Analysis completed and results written to output"
  priority: medium

reasoning:
  mode: deterministic
  autonomy_level: bounded
  confidence_threshold: 0.75

capabilities:
  tools:
    - read_asset
    - list_assets
  data_access:
    - asset_inventory

boundaries:
  risk_budget: medium
  allowed_actions:
    - agent_execute
    - read_asset
    - list_assets
  denied_actions:
    - delete_asset
  environment_scope:
    - staging
    - dev

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
    tsTemplate: `\
/**
 * {agentName} -- ZAK Generic Security Agent.
 *
 * Auto-generated by \`zak init\`. Implement execute() to define your agent's logic.
 */

import {
  BaseAgent,
  type AgentContext,
  type AgentResult,
  agentResultOk,
  registerAgent,
} from "@zeron/zak";

class {className} extends BaseAgent {
  /**
   * {agentName}
   *
   * General-purpose security agent. Replace this stub with your logic.
   */
  execute(context: AgentContext): AgentResult {
    // TODO: implement your security analysis logic here

    return agentResultOk(context, { status: "completed", findings: [] });
  }
}

registerAgent("{agentId}", {className}, {
  description: "{agentName}",
  version: "1.0.0",
  edition: "open-source",
});

export default {className};
`,
  },

  // -------------------------------------------------------------------------
  // Risk Quantification
  // -------------------------------------------------------------------------
  risk_quant: {
    domain: "risk_quant",
    yamlTemplate: `\
agent:
  id: {agentId}
  name: "{agentName}"
  domain: risk_quant
  version: "1.0.0"

intent:
  goal: "Compute and update risk scores for critical assets"
  success_criteria:
    - "All assets have updated risk scores in the SIF graph"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.75

capabilities:
  tools:
    - read_asset
    - list_assets
    - list_vulnerabilities
    - compute_risk
    - write_risk_node
  data_access:
    - asset_inventory
    - vulnerability_scanner

boundaries:
  risk_budget: medium
  allowed_actions:
    - agent_execute
    - read_asset
    - list_assets
    - compute_risk
    - write_risk_node
  denied_actions:
    - delete_asset
    - delete_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
    - require_confidence_threshold
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
    tsTemplate: `\
/**
 * {agentName} -- ZAK Risk Quantification Agent.
 *
 * Auto-generated by \`zak init\`. Implement execute() to define your agent's logic.
 */

import {
  BaseAgent,
  type AgentContext,
  type AgentResult,
  agentResultOk,
  registerAgent,
} from "@zeron/zak";

class {className} extends BaseAgent {
  /**
   * {agentName}
   *
   * Uses the ZAK risk propagation engine to compute and write risk scores.
   */
  execute(context: AgentContext): AgentResult {
    // 1. Load assets
    // const assets = await listAssets(context);

    // 2. Compute risk for each asset
    const results: Record<string, unknown>[] = [];

    // TODO: implement risk quantification logic
    // for (const asset of assets) {
    //   const risk = computeRisk(context, { ... });
    //   results.push({ assetId: asset.nodeId, ...risk });
    // }

    return agentResultOk(context, { results });
  }
}

registerAgent("risk_quant", {className}, {
  description: "{agentName}",
  version: "1.0.0",
  edition: "open-source",
});

export default {className};
`,
  },

  // -------------------------------------------------------------------------
  // Vulnerability Triage
  // -------------------------------------------------------------------------
  vuln_triage: {
    domain: "vuln_triage",
    yamlTemplate: `\
agent:
  id: {agentId}
  name: "{agentName}"
  domain: vuln_triage
  version: "1.0.0"

intent:
  goal: "Prioritize vulnerabilities based on risk and exploitability"
  success_criteria:
    - "Vulnerabilities ranked by priority score"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.85

capabilities:
  tools:
    - list_vulnerabilities
    - read_asset
    - compute_risk
  data_access:
    - vulnerability_scanner
    - asset_inventory

boundaries:
  risk_budget: low
  allowed_actions:
    - list_vulnerabilities
    - read_asset
    - compute_risk
  denied_actions:
    - patch_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
  sandbox_profile: standard
  audit_level: standard
`,
    tsTemplate: `\
/**
 * {agentName} -- ZAK Vulnerability Triage Agent.
 *
 * Auto-generated by \`zak init\`. Implement execute() to define your agent's logic.
 */

import {
  BaseAgent,
  type AgentContext,
  type AgentResult,
  agentResultOk,
  registerAgent,
} from "@zeron/zak";

class {className} extends BaseAgent {
  /**
   * {agentName}
   *
   * Prioritizes vulnerabilities by risk, exploitability, and asset criticality.
   */
  execute(context: AgentContext): AgentResult {
    // TODO: implement vulnerability triage logic
    // 1. List vulnerabilities
    // 2. Enrich with asset context
    // 3. Compute priority scores
    // 4. Return ranked results

    return agentResultOk(context, { triagedCount: 0, results: [] });
  }
}

registerAgent("vuln_triage", {className}, {
  description: "{agentName}",
  version: "1.0.0",
  edition: "open-source",
});

export default {className};
`,
  },

  // -------------------------------------------------------------------------
  // Application Security
  // -------------------------------------------------------------------------
  appsec: {
    domain: "appsec",
    yamlTemplate: `\
agent:
  id: {agentId}
  name: "{agentName}"
  domain: appsec
  version: "1.0.0"

intent:
  goal: "Scan code and dependencies for security vulnerabilities"
  success_criteria:
    - "All critical and high findings identified and written to SIF"
  priority: high

reasoning:
  mode: rule_based
  autonomy_level: bounded
  confidence_threshold: 0.80

capabilities:
  tools:
    - read_asset
    - list_assets
    - list_vulnerabilities
  data_access:
    - source_code
    - dependency_manifest

boundaries:
  risk_budget: low
  allowed_actions:
    - read_asset
    - list_assets
    - list_vulnerabilities
  denied_actions:
    - modify_source_code
    - delete_dependency
  environment_scope:
    - staging
    - dev

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
    tsTemplate: `\
/**
 * {agentName} -- ZAK AppSec Agent.
 *
 * Auto-generated by \`zak init\`. Implement execute() to define your agent's logic.
 */

import {
  BaseAgent,
  type AgentContext,
  type AgentResult,
  agentResultOk,
  registerAgent,
} from "@zeron/zak";

class {className} extends BaseAgent {
  /**
   * {agentName}
   *
   * Performs SAST/DAST scanning and writes findings to the SIF graph.
   */
  execute(context: AgentContext): AgentResult {
    const findings: Record<string, unknown>[] = [];

    // TODO: implement your SAST/DAST/dependency scanning logic here
    // 1. Scan source code for vulnerabilities
    // 2. Check dependency manifests for known CVEs
    // 3. Write findings to SIF graph

    return agentResultOk(context, {
      findingsCount: findings.length,
      findings,
    });
  }
}

registerAgent("appsec", {className}, {
  description: "{agentName}",
  version: "1.0.0",
  edition: "open-source",
});

export default {className};
`,
  },

  // -------------------------------------------------------------------------
  // Compliance
  // -------------------------------------------------------------------------
  compliance: {
    domain: "compliance",
    yamlTemplate: `\
agent:
  id: {agentId}
  name: "{agentName}"
  domain: compliance
  version: "1.0.0"

intent:
  goal: "Audit controls and generate compliance posture reports"
  success_criteria:
    - "All applicable controls evaluated against policy requirements"
  priority: medium

reasoning:
  mode: rule_based
  autonomy_level: bounded
  confidence_threshold: 0.80

capabilities:
  tools:
    - list_assets
    - read_asset
    - list_vulnerabilities
  data_access:
    - asset_inventory
    - policy_store

boundaries:
  risk_budget: low
  allowed_actions:
    - list_assets
    - read_asset
    - list_vulnerabilities
  denied_actions:
    - modify_policy
    - delete_control
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: verbose
`,
    tsTemplate: `\
/**
 * {agentName} -- ZAK Compliance Agent.
 *
 * Auto-generated by \`zak init\`. Implement execute() to define your agent's logic.
 */

import {
  BaseAgent,
  type AgentContext,
  type AgentResult,
  agentResultOk,
  registerAgent,
} from "@zeron/zak";

class {className} extends BaseAgent {
  /**
   * {agentName}
   *
   * Evaluates controls against compliance frameworks and generates posture reports.
   */
  execute(context: AgentContext): AgentResult {
    // TODO: implement compliance audit logic
    // 1. Load applicable controls and policies
    // 2. Evaluate each control against requirements
    // 3. Generate compliance posture report

    return agentResultOk(context, {
      framework: "custom",
      controlsEvaluated: 0,
      compliant: 0,
      nonCompliant: 0,
      results: [],
    });
  }
}

registerAgent("compliance", {className}, {
  description: "{agentName}",
  version: "1.0.0",
  edition: "open-source",
});

export default {className};
`,
  },
};
