// Package cli provides the ZAK CLI commands and domain templates for agent scaffolding.
package cli

// DomainTemplate holds the scaffolding templates for a single security domain.
type DomainTemplate struct {
	// Domain is the US-ADSL domain identifier (e.g. "risk_quant").
	Domain string

	// YAMLTemplate is a Go text/template string for the agent YAML definition.
	// Placeholders: {{.AgentID}}, {{.AgentName}}
	YAMLTemplate string

	// GoTemplate is a Go text/template string for the agent Go source file.
	// Placeholders: {{.AgentID}}, {{.AgentName}}, {{.ClassName}}
	GoTemplate string
}

// OSSDomains lists the open-source domain identifiers available in `zak init`.
var OSSDomains = []string{
	"generic",
	"risk_quant",
	"vuln_triage",
	"appsec",
	"compliance",
}

// DomainTemplates maps domain names to their scaffolding templates.
var DomainTemplates = map[string]*DomainTemplate{
	"generic": {
		Domain: "generic",
		YAMLTemplate: `agent:
  id: {{.AgentID}}
  name: "{{.AgentName}}"
  domain: appsec
  version: "1.0.0"

intent:
  goal: "Perform a general-purpose security analysis"
  success_criteria:
    - "Analysis completed and results written to output"
  priority: medium

reasoning:
  mode: deterministic
  autonomy_level: bounded
  confidence_threshold: 0.75

capabilities:
  tools:
    - read_asset
    - list_assets
  data_access:
    - asset_inventory

boundaries:
  risk_budget: medium
  allowed_actions:
    - agent_execute
    - read_asset
    - list_assets
  denied_actions:
    - delete_asset
  environment_scope:
    - staging
    - dev

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
		GoTemplate: `// Package agents contains ZAK agent implementations.
package agents

// {{.AgentName}} -- ZAK Generic Security Agent.
//
// Auto-generated by zak init. Implement Execute() to define your agent logic.

import (
	"github.com/securezeron/zeron-agent-development-kit/adk/go/pkg/runtime"
)

func init() {
	runtime.RegisterAgent("appsec", func() runtime.BaseAgent {
		return &{{.ClassName}}{}
	},
		runtime.WithDescription("{{.AgentName}}"),
		runtime.WithVersion("1.0.0"),
		runtime.WithEdition("open-source"),
		runtime.WithClassName("{{.ClassName}}"),
	)
}

// {{.ClassName}} is a general-purpose security agent.
type {{.ClassName}} struct{}

func (a *{{.ClassName}}) Execute(ctx *runtime.AgentContext) (*runtime.AgentResult, error) {
	// TODO: implement your agent logic here
	output := map[string]interface{}{
		"status": "completed",
	}
	return runtime.ResultOk(ctx, output, 0), nil
}
`,
	},
	"risk_quant": {
		Domain: "risk_quant",
		YAMLTemplate: `agent:
  id: {{.AgentID}}
  name: "{{.AgentName}}"
  domain: risk_quant
  version: "1.0.0"

intent:
  goal: "Compute and update risk scores for critical assets"
  success_criteria:
    - "All assets have updated risk scores in the SIF graph"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.75

capabilities:
  tools:
    - read_asset
    - list_assets
    - list_vulnerabilities
    - compute_risk
    - write_risk_node
  data_access:
    - asset_inventory
    - vulnerability_scanner

boundaries:
  risk_budget: medium
  allowed_actions:
    - agent_execute
    - read_asset
    - list_assets
    - compute_risk
    - write_risk_node
  denied_actions:
    - delete_asset
    - delete_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
    - require_confidence_threshold
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
		GoTemplate: `// Package agents contains ZAK agent implementations.
package agents

// {{.AgentName}} -- ZAK Risk Quantification Agent.
//
// Auto-generated by zak init. Implement Execute() to define your agent logic.
// Register with: runtime.RegisterAgent(domain="risk_quant")

import (
	"github.com/securezeron/zeron-agent-development-kit/adk/go/pkg/runtime"
)

func init() {
	runtime.RegisterAgent("risk_quant", func() runtime.BaseAgent {
		return &{{.ClassName}}{}
	},
		runtime.WithDescription("{{.AgentName}}"),
		runtime.WithVersion("1.0.0"),
		runtime.WithEdition("open-source"),
		runtime.WithClassName("{{.ClassName}}"),
	)
}

// {{.ClassName}} uses the ZAK risk propagation engine to compute and write risk scores.
type {{.ClassName}} struct{}

func (a *{{.ClassName}}) Execute(ctx *runtime.AgentContext) (*runtime.AgentResult, error) {
	// 1. Load assets via tools
	// 2. Compute risk for each asset
	// 3. Write risk nodes to the SIF graph

	results := []map[string]interface{}{}
	output := map[string]interface{}{
		"results": results,
	}
	return runtime.ResultOk(ctx, output, 0), nil
}
`,
	},
	"vuln_triage": {
		Domain: "vuln_triage",
		YAMLTemplate: `agent:
  id: {{.AgentID}}
  name: "{{.AgentName}}"
  domain: vuln_triage
  version: "1.0.0"

intent:
  goal: "Prioritize vulnerabilities based on risk"
  success_criteria:
    - "Vulnerabilities ranked by priority score"
  priority: high

reasoning:
  mode: probabilistic
  autonomy_level: bounded
  confidence_threshold: 0.85

capabilities:
  tools:
    - list_vulnerabilities
    - read_asset
    - compute_priority
  data_access:
    - vulnerability_scanner
    - asset_inventory

boundaries:
  risk_budget: low
  allowed_actions:
    - list_vulnerabilities
    - read_asset
    - compute_priority
  denied_actions:
    - patch_vulnerability
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
  sandbox_profile: standard
  audit_level: standard
`,
		GoTemplate: `// Package agents contains ZAK agent implementations.
package agents

// {{.AgentName}} -- ZAK Vulnerability Triage Agent.
//
// Auto-generated by zak init. Implement Execute() to define your agent logic.

import (
	"github.com/securezeron/zeron-agent-development-kit/adk/go/pkg/runtime"
)

func init() {
	runtime.RegisterAgent("vuln_triage", func() runtime.BaseAgent {
		return &{{.ClassName}}{}
	},
		runtime.WithDescription("{{.AgentName}}"),
		runtime.WithVersion("1.0.0"),
		runtime.WithEdition("open-source"),
		runtime.WithClassName("{{.ClassName}}"),
	)
}

// {{.ClassName}} prioritizes vulnerabilities by computing risk-based priority scores.
type {{.ClassName}} struct{}

func (a *{{.ClassName}}) Execute(ctx *runtime.AgentContext) (*runtime.AgentResult, error) {
	// TODO: implement vulnerability triage logic
	output := map[string]interface{}{
		"triaged_count": 0,
		"results":       []map[string]interface{}{},
	}
	return runtime.ResultOk(ctx, output, 0), nil
}
`,
	},
	"appsec": {
		Domain: "appsec",
		YAMLTemplate: `agent:
  id: {{.AgentID}}
  name: "{{.AgentName}}"
  domain: appsec
  version: "1.0.0"

intent:
  goal: "Scan code and dependencies for security vulnerabilities"
  success_criteria:
    - "All critical/high findings identified and written to SIF"
  priority: high

reasoning:
  mode: rule_based
  autonomy_level: bounded
  confidence_threshold: 0.80

capabilities:
  tools:
    - sast_scan
    - dependency_scan
    - write_vulnerability_node
  data_access:
    - source_code
    - dependency_manifest

boundaries:
  risk_budget: low
  allowed_actions:
    - sast_scan
    - dependency_scan
    - write_vulnerability_node
  denied_actions:
    - modify_source_code
    - delete_dependency
  environment_scope:
    - staging
    - dev

safety:
  guardrails:
    - no_destructive_actions
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
		GoTemplate: `// Package agents contains ZAK agent implementations.
package agents

// {{.AgentName}} -- ZAK AppSec Agent.
//
// Auto-generated by zak init. Implement Execute() to define your agent logic.

import (
	"github.com/securezeron/zeron-agent-development-kit/adk/go/pkg/runtime"
)

func init() {
	runtime.RegisterAgent("appsec", func() runtime.BaseAgent {
		return &{{.ClassName}}{}
	},
		runtime.WithDescription("{{.AgentName}}"),
		runtime.WithVersion("1.0.0"),
		runtime.WithEdition("open-source"),
		runtime.WithClassName("{{.ClassName}}"),
	)
}

// {{.ClassName}} performs SAST/DAST scanning and writes findings as VulnerabilityNodes to the SIF graph.
type {{.ClassName}} struct{}

func (a *{{.ClassName}}) Execute(ctx *runtime.AgentContext) (*runtime.AgentResult, error) {
	// TODO: implement your SAST/DAST/dependency scanning logic here
	output := map[string]interface{}{
		"findings_count": 0,
		"findings":       []map[string]interface{}{},
	}
	return runtime.ResultOk(ctx, output, 0), nil
}
`,
	},
	"compliance": {
		Domain: "compliance",
		YAMLTemplate: `agent:
  id: {{.AgentID}}
  name: "{{.AgentName}}"
  domain: compliance
  version: "1.0.0"

intent:
  goal: "Evaluate compliance posture against regulatory frameworks"
  success_criteria:
    - "Compliance controls assessed and gaps identified"
  priority: high

reasoning:
  mode: rule_based
  autonomy_level: bounded
  confidence_threshold: 0.80

capabilities:
  tools:
    - list_controls
    - evaluate_control
    - write_compliance_node
  data_access:
    - policy_repository
    - control_framework

boundaries:
  risk_budget: low
  allowed_actions:
    - list_controls
    - evaluate_control
    - write_compliance_node
  denied_actions:
    - modify_policy
    - delete_control
  environment_scope:
    - production
    - staging

safety:
  guardrails:
    - no_destructive_actions
    - require_confidence_threshold
    - redact_secrets
  sandbox_profile: standard
  audit_level: standard
`,
		GoTemplate: `// Package agents contains ZAK agent implementations.
package agents

// {{.AgentName}} -- ZAK Compliance Agent.
//
// Auto-generated by zak init. Implement Execute() to define your agent logic.

import (
	"github.com/securezeron/zeron-agent-development-kit/adk/go/pkg/runtime"
)

func init() {
	runtime.RegisterAgent("compliance", func() runtime.BaseAgent {
		return &{{.ClassName}}{}
	},
		runtime.WithDescription("{{.AgentName}}"),
		runtime.WithVersion("1.0.0"),
		runtime.WithEdition("open-source"),
		runtime.WithClassName("{{.ClassName}}"),
	)
}

// {{.ClassName}} evaluates compliance posture against regulatory frameworks.
type {{.ClassName}} struct{}

func (a *{{.ClassName}}) Execute(ctx *runtime.AgentContext) (*runtime.AgentResult, error) {
	// TODO: implement compliance evaluation logic
	output := map[string]interface{}{
		"controls_assessed": 0,
		"gaps_found":        0,
		"results":           []map[string]interface{}{},
	}
	return runtime.ResultOk(ctx, output, 0), nil
}
`,
	},
}
