window.LIVE_EMAILS = [
  {
    "uid": "raw-0",
    "from_raw": "uqlc26re39@wnbaldwy.com ",
    "from_domain": "wnbaldwy.com",
    "display_name": "uqlc26re39@wnbaldwy.com",
    "subject": "old domain",
    "date": "2026-04-16 09:33",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'wnbaldwy.com' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "mtdex34575@minitts.net ",
    "from_domain": "minitts.net",
    "display_name": "mtdex34575@minitts.net",
    "subject": "new mail",
    "date": "2026-04-16 09:32",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "ipahjbmeagiachctmq@vtmpj.com ",
    "from_domain": "vtmpj.com",
    "display_name": "ipahjbmeagiachctmq@vtmpj.com",
    "subject": "new mail",
    "date": "2026-04-16 09:29",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'vtmpj.com' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "uqlc26re39@wnbaldwy.com ",
    "from_domain": "wnbaldwy.com",
    "display_name": "uqlc26re39@wnbaldwy.com",
    "subject": "email",
    "date": "2026-04-16 09:28",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "uqlc26re39@wnbaldwy.com ",
    "from_domain": "wnbaldwy.com",
    "display_name": "uqlc26re39@wnbaldwy.com",
    "subject": "old email",
    "date": "2026-04-16 07:19",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "mohoki4634@tatefarm.com ",
    "from_domain": "tatefarm.com",
    "display_name": "mohoki4634@tatefarm.com",
    "subject": "new email",
    "date": "2026-04-16 07:17",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'tatefarm.com' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "Orcella.Zarrella@AllWebEmails.com ",
    "from_domain": "allwebemails.com",
    "display_name": "Orcella.Zarrella@AllWebEmails.com",
    "subject": "new",
    "date": "2026-04-15 14:21",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "mohoki4634@tatefarm.com ",
    "from_domain": "tatefarm.com",
    "display_name": "mohoki4634@tatefarm.com",
    "subject": "hie",
    "date": "2026-04-15 14:20",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'tatefarm.com' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "ocqjk81546@minitts.net ",
    "from_domain": "minitts.net",
    "display_name": "ocqjk81546@minitts.net",
    "subject": "oldone",
    "date": "2026-04-12 13:42",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'minitts.net' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "ocqjk81546@minitts.net ",
    "from_domain": "minitts.net",
    "display_name": "ocqjk81546@minitts.net",
    "subject": "newone",
    "date": "2026-04-12 13:41",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "uncomfortable836@deltajohnsons.com ",
    "from_domain": "deltajohnsons.com",
    "display_name": "uncomfortable836@deltajohnsons.com",
    "subject": "newone",
    "date": "2026-04-12 13:37",
    "risk_level": "SAFE",
    "action": "ALLOW",
    "reasons": [],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": true,
    "body_preview": "No preview available for security reasons."
  },
  {
    "uid": "raw-0",
    "from_raw": "fodyhywy@denipl.com ",
    "from_domain": "denipl.com",
    "display_name": "fodyhywy@denipl.com",
    "subject": "GT VS LSG",
    "date": "2026-04-12 13:34",
    "risk_level": "MEDIUM_RISK",
    "action": "WARN",
    "reasons": [
      "Sender domain 'denipl.com' is not in the approved whitelist"
    ],
    "flags": {},
    "spf_pass": true,
    "dkim_pass": true,
    "dmarc_pass": true,
    "in_whitelist": false,
    "body_preview": "No preview available for security reasons."
  }
];
